export const ROLES = {
  ADMIN: 'ADMIN',
  DRIVER: 'DRIVER',
  STUDENT: 'STUDENT',
};

export const BUS_STATUS = {
  ACTIVE: 'ACTIVE',
  MAINTENANCE: 'MAINTENANCE',
  INACTIVE: 'INACTIVE',
};

export const TRIP_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const DRIVER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ON_LEAVE: 'ON_LEAVE',
};

export const TRIP_EVENT_TYPES = {
  ARRIVED: 'ARRIVED',
  DEPARTED: 'DEPARTED',
  SKIPPED: 'SKIPPED',
};

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  SERVER_ERROR: 'SERVER_ERROR',
  GPS_PERMISSION_DENIED: 'GPS_PERMISSION_DENIED',
  INVALID_COORDINATES: 'INVALID_COORDINATES',
  TRIP_NOT_ACTIVE: 'TRIP_NOT_ACTIVE',
};

// GPS simulation
export const GPS_CONFIG = {
  USE_SIMULATED: process.env.USE_SIMULATED_GPS === 'true',
  UPDATE_INTERVAL: parseInt(process.env.SIMULATED_GPS_UPDATE_INTERVAL || '5000'),
  MIN_ACCURACY: 5,
  MAX_ACCURACY: 50,
};

// Location broadcast settings
export const LOCATION_CONFIG = {
  STALE_TIMEOUT: 60000, // 60 seconds
  BATCH_SIZE: 100,
};

// ETA calculation
export const ETA_CONFIG = {
  AVERAGE_SPEED_KMH: 30,
  DEFAULT_STOP_TIME: 30, // seconds
};
